import { LastSeason } from './LastSeason';
import { ProductImage } from './ProductImage';
import { ProductColor } from './ProductColor';
import { SizeRun } from './SizeRun';

export class Product {
  id: number;
  thumbnail: boolean;
  quantities: number;
  specialInstructions: string;
  mainImg: ProductImage;
  color: ProductColor;
  sizeRun: SizeRun;
  sku: string;
  customerSku: null;
  price: number;
  customerNumber: null;
  customerShipTo: null;
  style: string;
  factoryStyle: null;
  construction: string;
  productName: string;
  productType: string;
  isMakeup: boolean;
  factory: string;
  brand: string;
  box: string;
  boxLength: number;
  boxWidth: number;
  boxHeight: number;
  boxWeight: number;
  department: string;
  description: string;
  catalogPage: string;
  purchaseOrder: string;
  customerPurchaseOrder: string;
  keywords: string[];
  collageImg: null;
  specSheetImg: null;
  lastSeason: LastSeason;
  upc: string;
  classCode: string;
  whslPriceCurr: number;
  whslPriceOrig: number;
  retailPriceCurr: number;
  retailPriceOrig: number;
  msrp: number;
  firstCost: number;
  dutyPerc: number;
  agentPerc: number;
  freightCost: number;
  officeCost: number;
  landedCost: number;
  availableQty: number;
  bookedQty: number;
  futureAvlQty: number;
  totalAvlQty: number;
  futureQty1: number;
  etaStart1: string;
  etaEnd1: string;
  futureQty2: number;
  etaStart2: string;
  etaEnd2: string;
  futureQty3: number;
  etaStart3: string;
  etaEnd3: string;
  futureQty4: number;
  etaStart4: string;
  etaEnd4: string;
  caseLength: number;
  caseWidth: number;
  caseHeight: number;
  caseWeight: number;
  isActive: boolean;
  dateCreated: Date;
  dateModified: Date;
  dateDeleted: null;
  children?: Array<ProductChild> = [];
}

export class ProductChild {
  size: string;
  upc: string;
}
